image: debian:testing-slim

before_script:
  - apt-get update
  - apt-get install -y simgrid cmake build-essential libboost-dev

test:
  script:
  - cmake .
  - make VERBOSE=1
  - ./sample-simulator cluster_platform.xml

