image: simgrid/stable

before_script:
  - apt-get update
  - apt-get install -y cmake build-essential libboost-dev

test:
  script:
  - cmake .
  - make VERBOSE=1
  - ./sample-simulator cluster_platform.xml

