# Test that the git version of this template compiles on the simgrid/unstable docker image 
.build_git: &build_git
  script:
  - apt-get update
  - apt-get install -y cmake build-essential libboost-dev
  - cmake .
  - make VERBOSE=1
  - ./master-workers small_platform.xml master-workers_d.xml
  - ./ping-pong cluster_platform.xml

test-git-stable:
  image: simgrid/stable
  <<: *build_git

test-git-stable-3.22:
  image: simgrid/stable:v3.22.2
  <<: *build_git
    
test-git-stable-3.21:
  image: simgrid/stable:v3_21
  <<: *build_git

test-git-stable-3.20:
  image: simgrid/stable:v3.20
  <<: *build_git


# Test that the simgrid/tuto-s4u docker image is usable as advised in tuto
test-image:
  image: simgrid/tuto-s4u
  script:
  - mkdir /source/tutorial # create the pseudo-volume
  - cp -r /source/simgrid-template-s4u.git/* /source/tutorial
  - cd /source/tutorial
  - cmake .
  - make VERBOSE=1
  - ./master-workers small_platform.xml master-workers_d.xml
  - ./ping-pong cluster_platform.xml
 